language: node_js
node_js:
- '8'
after_success:
- yarn build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: target-branch
  fqdn: peterdemartini.com
  email: thepeterdemartini@gmail.com
  name: Deploy Bot
  on:
    branch: master
    repo: peterdemartini/blog
